name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew && ./gradlew assembleRelease
        tree app/build/outputs/apk/release

    - name: Upload APK
      uses: actions/upload-artifact@v4.3.5
      with:
        name: APK
        path: app/build/outputs/apk/release/*.apk
